### PR TITLE
IPLT-5303 transferred grid from gnui

### PR DESCRIPTION
**Pull request by arkniazi**
I have moved grid story from the GNUI design system

Screenshot 2024-02-08 at 2 40 38 PM

### CODE REVIEW

**Comment by MrMrsic** [comment]
@arkniazi a few questions regarding `react-awesome-styled-grid`
- is it still active Grid solution or is it deprecated?
- is `void 0 === i && (i = global);` change in node_modules really necessary? (I don't like manual changes inside of node_modules, except is is really only option left)

**Comment by arkniazi** [comment]
> @arkniazi a few questions regarding `react-awesome-styled-grid`
> 
> * is it still active Grid solution or is it deprecated?
> * is `void 0 === i && (i = global);` change in node_modules really necessary? (I don't like manual changes inside of node_modules, except is is really only option left)

I didn't need to apply any changes in the node_modules to make this library work in here. 
And you are right we shouldn't be making any changes to the node_modules.  I'll check what's the patch about.

**Comment by MrMrsic** [comment]
Ok, yeah please check - because I was confused as I was reading through Foundations/Grid story seeing "deprecated" and manual node_modules changes.
We can keep `react-awesome-styled-grid` if it is in good place and functional, but if not - there are many alternatives out there: [react-grid-system](https://www.npmjs.com/package/react-grid-system), [react-grid](https://www.npmjs.com/package/react-grid)

**Comment by MrMrsic** [comment]
Also, instead of just having story which describes npm usage - why don't we make a Grid component (by utilizing that npm package) which will show all it's props (inherited from the npm package).
What do you think @arkniazi ?

**Comment by MrMrsic** [comment]
ping @arkniazi - how are things coming along? any blockers/updates?

**Comment by arkniazi** [comment]
> ping @arkniazi - how are things coming along? any blockers/updates?

Sorry I just checked your message now. No blockers I couldn't find any issue reported on the github repo. So we can just update this documentation accordingly.

**Review by MrMrsic — APPROVED** [review]
looks good

**Pull request merged**
