### PR TITLE
feat: workflows

### PR DESCRIPTION
**Pull request by arkniazi**
IPLT-5355 updated npm secret and commented out chromatic release workflow

### CODE REVIEW

**Comment by MrMrsic** [comment]
@arkniazi will this Github Action configuration trigger NPM package publishing ? on new release event?
image

**Comment by arkniazi** [comment]
> @arkniazi will this Github Action configuration trigger NPM package publishing ? on new release event? image

If we stick to default settings in the workflows then yes. Because I just commented out configuration for this. I thought we were going for auto deployment.

**Comment by MrMrsic** [comment]
I see. Ok. Just to confirm - current workflow will publish our repo to NPM automatically in the moment we push to "master" branch? 
(in our case that will be PR going from "production" branch to "master" branch)

**Comment by MrMrsic** [comment]
I will merge it so we can test publishing

**Review by MrMrsic — APPROVED** [review]

**Pull request merged**
